name: CI

on:
  push:
  pull_request;

jobs:
  test:
    runs-on: ubuntu-latest
    stategy:
      matrix:
        java: [21, 25]
        experimental: [false, true]
        exclude:
          - java: 21
            experimental: true
          - java: 25
            experimental: false
    continue-on-error: ${{ matrix.experimental }}


    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: maven
      
      - name: Run tests
        run: ./mvnw -B -ntp clean test